---
name: konquest
version: 17.08.1
summary: Galactic Strategy Game
description: Konquest is a version of Gnu-Lactic Konquest. Players conquer other planets
    by sending ships to them. The goal is to build an interstellar empire and ultimately
    conquer all other player's planets.
confinement: strict
grade: stable
apps:
    konquest:
        command: kf5-launch konquest
        plugs:
        - kde-frameworks-5-plug
        - home
        - x11
        - opengl
        - network
        - network-bind
        - unity7
        - pulseaudio
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.konquest
        bus: session
plugs:
    kde-frameworks-5-plug:
        content: kde-frameworks-5-all
        interface: content
        default-provider: kde-frameworks-5
        target: kf5
parts:
    konquest:
        after:
        - kde-frameworks-5-dev
        - kde-frameworks-5-env
        plugin: cmake
        build-packages:
        - libkf5doctools-dev
        - libkf5kdegames-dev
        - libpulse0
        source: https://download.kde.org/stable/applications/17.08.1/src/konquest-17.08.1.tar.xz
        configflags:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
